/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace NFTFactory {
  export type CollectionInfoStruct = {
    contractAddress: AddressLike;
    creator: AddressLike;
    name: string;
    symbol: string;
    deployedAt: BigNumberish;
  };

  export type CollectionInfoStructOutput = [
    contractAddress: string,
    creator: string,
    name: string,
    symbol: string,
    deployedAt: bigint
  ] & {
    contractAddress: string;
    creator: string;
    name: string;
    symbol: string;
    deployedAt: bigint;
  };
}

export interface NFTFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "collections"
      | "createCollection"
      | "creatorCollections"
      | "deployFee"
      | "getAllCollections"
      | "getCollectionsByCreator"
      | "isRegistered"
      | "platformFeeRecipient"
      | "setDeployFee"
      | "totalCollections"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CollectionCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "collections",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCollection",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorCollections",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deployFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllCollections",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectionsByCreator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDeployFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCollections",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "collections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deployFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectionsByCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDeployFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCollections",
    data: BytesLike
  ): Result;
}

export namespace CollectionCreatedEvent {
  export type InputTuple = [
    collection: AddressLike,
    creator: AddressLike,
    name: string,
    symbol: string
  ];
  export type OutputTuple = [
    collection: string,
    creator: string,
    name: string,
    symbol: string
  ];
  export interface OutputObject {
    collection: string;
    creator: string;
    name: string;
    symbol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NFTFactory extends BaseContract {
  connect(runner?: ContractRunner | null): NFTFactory;
  waitForDeployment(): Promise<this>;

  interface: NFTFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  collections: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint] & {
        contractAddress: string;
        creator: string;
        name: string;
        symbol: string;
        deployedAt: bigint;
      }
    ],
    "view"
  >;

  createCollection: TypedContractMethod<
    [
      name: string,
      symbol: string,
      maxSupply: BigNumberish,
      mintPrice: BigNumberish,
      whitelistPrice: BigNumberish,
      maxWLPerWallet: BigNumberish,
      royaltyBps: BigNumberish
    ],
    [string],
    "payable"
  >;

  creatorCollections: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  deployFee: TypedContractMethod<[], [bigint], "view">;

  getAllCollections: TypedContractMethod<
    [],
    [NFTFactory.CollectionInfoStructOutput[]],
    "view"
  >;

  getCollectionsByCreator: TypedContractMethod<
    [creator: AddressLike],
    [string[]],
    "view"
  >;

  isRegistered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  platformFeeRecipient: TypedContractMethod<[], [string], "view">;

  setDeployFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalCollections: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "collections"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint] & {
        contractAddress: string;
        creator: string;
        name: string;
        symbol: string;
        deployedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCollection"
  ): TypedContractMethod<
    [
      name: string,
      symbol: string,
      maxSupply: BigNumberish,
      mintPrice: BigNumberish,
      whitelistPrice: BigNumberish,
      maxWLPerWallet: BigNumberish,
      royaltyBps: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "creatorCollections"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "deployFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllCollections"
  ): TypedContractMethod<[], [NFTFactory.CollectionInfoStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getCollectionsByCreator"
  ): TypedContractMethod<[creator: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformFeeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setDeployFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalCollections"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "CollectionCreated"
  ): TypedContractEvent<
    CollectionCreatedEvent.InputTuple,
    CollectionCreatedEvent.OutputTuple,
    CollectionCreatedEvent.OutputObject
  >;

  filters: {
    "CollectionCreated(address,address,string,string)": TypedContractEvent<
      CollectionCreatedEvent.InputTuple,
      CollectionCreatedEvent.OutputTuple,
      CollectionCreatedEvent.OutputObject
    >;
    CollectionCreated: TypedContractEvent<
      CollectionCreatedEvent.InputTuple,
      CollectionCreatedEvent.OutputTuple,
      CollectionCreatedEvent.OutputObject
    >;
  };
}
